# Generated by Django 5.0.6 on 2024-06-15 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="articles.article"
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="comment",
            field=models.CharField(max_length=140),
        ),
    ]
