# Generated by Django 5.0.6 on 2024-07-17 19:59

import django_summernote.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0003_alter_comment_article_alter_comment_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="body",
            field=django_summernote.fields.SummernoteTextField(),
        ),
    ]
