# Generated by Django 5.0.6 on 2024-07-18 20:44

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0004_alter_article_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="body",
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
