# Generated by Django 5.0.6 on 2024-10-02 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0001_initial"),
        ("tutorials", "0003_alter_unit_content"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="unit",
            name="course",
        ),
        migrations.AlterField(
            model_name="quiz",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tutorials.unit"
            ),
        ),
        migrations.DeleteModel(
            name="Course",
        ),
        migrations.DeleteModel(
            name="Unit",
        ),
    ]
