# Generated by Django 5.0.6 on 2024-10-02 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutorials", "0002_alter_course_description_alter_unit_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unit",
            name="content",
            field=models.TextField(blank=True),
        ),
    ]
