# Generated by Django 5.0.6 on 2024-10-02 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutorials", "0003_alter_unit_content"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="unit",
            name="course",
        ),
        migrations.AlterField(
            model_name="unit",
            name="content",
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name="Course",
        ),
    ]
